##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
	# Plugin configuration
	#  [plugins.inputs]
	#  foo = "bar"

[build]
# Dummy build command
command = "bash ./scripts/netlify_build.sh"
publish = "public"

[build.environment]
GO_VERSION = "1.20.4"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.111.3"
NODE_VERSION = "16"
TZ="America/Toronto"
