##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
	# Plugin configuration
	#  [plugins.inputs]
	#  foo = "bar"

[build]
# Dummy build command
command = "echo onBuild && mkdir dist"

[build.environment]
GO_VERSION = "1.20.4"
NODE_VERSION = "18.16.0"
